// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetImageInfo
       * @returns {Promise<ImageInfo>}  - Go Type: main.ImageInfo
       */
      "GetImageInfo": () => {
        return window.go.main.App.GetImageInfo();
      },
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
      /**
       * SetWallpaper
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SetWallpaper": (arg1) => {
        return window.go.main.App.SetWallpaper(arg1);
      },
    },
  },

};
export default go;
